### ISSUE TITLE
Make Documentation Ready for Release

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/cryptimeleon.github.io#1]
Due to the math rewrite, work on the documentation has been halted until now. Once the next release is feature-complete, we should write documentation to support the release.

# Ideas

My plans for the documentation currently would be as follows:
- Update readmes to give the potential user a better idea of the purpose of this library.
- Installation guide (esp. for the mcl wrapper). 
- Overview of the libraries: What does each do and which one is relevant for me?
- There should be a short tutorial that gives a basic overview of the features of math/craco and guides the user through implementing a sample construction. @JanBobolz was planning on writing this. This would be part of a "getting started" section.
Compared to my old ElGamal tutorial, this should be much shorter and more digestible. More of a quickstart type of thing.
- A guide for contributing to the project. This could also also be part of a `contributors.md` file as seen in other github projects. 
This should include information on the technical details of contribution, e.g. forking and creating pull request.
Could also include information on some relevant internals of the project. For example, how to add new pairing wrappers.
- A link to the javadocs for each of the sublibraries. We could use [javadoc.io](www.javadoc.io) to host the java docs.
- FAQ
- A tutorial on using representations as well as serializing a representation.
- Somewhere there should be something on how to use pairings, perhaps this could be part of a longer tutorial on for example some simple pairing-based construction such as the BLS signature. This would be more akin to the old ElGamal tutorial I wrote.
Can integrate basics of using representations here.
- For each type of scheme we could just quickly detail which interfaces are relevant. Can point to example constructions here.
- Benchmarking: Example using JMH, Group operation counting.

## FAQ questions

- Is the library cross-platform?
- How do I report a bug/suggest improvements?

# DONE

- Updated installation guide
- Library Overview
- Tutorials by Jan on Basics, Pairings, and Protocols
- FAQ (still short)
- Representations Tutorial
- Benchmarking Page

# TODO

- Could still add an example where we use JMH for benchmarking a function to the Benchmark page
- Update readmes

**Comment by JanBobolz** [comment]
Can we make it so that https://upbcuk.github.io doesn't show a 404?

**Comment by rheitjoh** [comment]
> Can we make it so that https://upbcuk.github.io doesn't show a 404?

Did that. Required a change of reporitory name though.

**Comment by rheitjoh** [comment]
Also need to decide what to do with my ElGamal tutorial. We could keep it as an example for possible class structure since the other tutorial don't really deal with that, and it also includes some basic stuff about representations. Don't want to clutter the getting started section too much though, so maybe move it somewhere else?
