### ISSUE TITLE
Create script for automatic conversion of Jupyter notebooks to Markdown

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/cryptimeleon.github.io#12]
To be able to render Jupyter notebooks on the documentation page, they need to be converted to the Markdown format supported by the Kramdown parser we use.
The conversion included in Jupyter does not do this correctly; therefore, a script to automate the process would be useful.

The script has to:
- Replace all single dollar signs $ with double dollar signs $$ as that is the [default used by Kramdown](https://kramdown.gettalong.org/syntax.html#math-blocks)
- Replace \`\`\`Java with \`\`\`java to make code highlighting work properly
- Create a valid YAML Front Matter:
    * The first header is usually used as a title. Therefore we should remove the header and use it as the Front Matter Title. Remember to wrap it in quotation marks; otherwise, things such as ":" will be interpreted as YAML
    * Enable `mathjax: true` and/or `toc: true` to render LaTex and/or a table of contents. Could use optional commandline arguments to make this configurable.
- Extract images from Notebooks, store them in the `assets` folder, and update the link in the Markdown file

There is already an existing [Jupyter Notebook to Jekyll Markdown converter](https://pypi.org/project/jekyllnb/).
We could use that via a Github Actions workflow to automatically do the conversion like [here](https://github.com/klane/databall/blob/master/.github/workflows/gh-pages.yml). It does require adding additional metadata to the Notebook to enable YAML Front Matter (as shown on the script's page).

**Comment by JanBobolz** [comment]
I've just tried the converter you linked. (1) It does _not_ convert the dollar signs. (2) Any code blocks are assumed to be python. (3) It does not extract images. 
So overall, I don't think that fits our use-case as is.

In addition to the points you list, the converter we write should also generate the text snippet explaining to the reader that the notebook can be executed via binder.

**Comment by rheitjoh** [comment]
It is also possible to convert the Notebook directly to HTML instead, which preserves the look of the notebook perfectly. However, the rendered page then has different styling and no navigation sidebar, since it is not run through any conversion process.

**Comment by JanBobolz** [comment]
I'd say that's an option should our script plan turn out to be too time-consuming.

**Comment by rheitjoh** [comment]
I started on the script [here](https://github.com/rheitjoh/nb-to-jekyll).

**Comment by rheitjoh** [comment]
I think this issue has been sufficiently addressed for now. Any more feature requests should be posted on the [nbtojekyll github page](https://mmistakes.github.io/minimal-mistakes).
