### ISSUE TITLE
Tidy up the ipynb-based tutorials

### ISSUE THREAD

**Issue by JanBobolz** [cryptimeleon/cryptimeleon.github.io#2]
Find nice way to include the ipynb stuff.

Ideas:
- Add a link to spin up a [binder](https://mybinder.org) instance.
  - Ideally contains all the md files from the github.io site and the `ipynb`s where appropriate.
  - Can only be usefully done once we've deployed the project to maven central.
- Somehow get rid of the markdown versions of the files and just have github render the ipynb. It seems to do [a pretty good job](https://github.com/upbcuk/upb.crypto.docs/blob/gh-pages/getting-started/5-minute-tutorial.ipynb) with that.
- If the above is not possible: Include missing pictures into the md files and fix mathjax and code/output style.

**Comment by rheitjoh** [comment]
Opted to fix the markdown version for now (just for the 5-minute tutorial for now, can also do other one if we decide to go that route). Mathjax wants `\\( \\)` type math tags by the way, dollar sign does not work. Which pictures do you mean btw? The emojis seem to work just fine. Also, the ` ```Java` code block does not work, it needs to be ` ```java` with `java` in lower case for proper syntax highlighting.

How does binder help btw? I tried it and it seems to just spin up the usual IPython server. Not sure how we would include that in our website.

[Github docs](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/working-with-jupyter-notebook-files-on-github) just recommend to convert the python notebooks to a renderable file format as you did by converting it to markdown.

**Comment by JanBobolz** [comment]
> How does binder help btw? I tried it and it seems to just spin up the usual IPython server. Not sure how we would include that in our website.

There's a [website](https://mybinder.org) that would basically host that jupyter server for us. So we could include a button in our documentation that would allow anyone to directly try out our library (e.g., the 5-minute tutorial) in their browser with a simple click. So we could make tutorials more interactive (though admittedly, my current 5-minute tutorial is pretty much just "execute this code" - I'm undecided whether we can/should do something more engaging there).

**Comment by rheitjoh** [comment]
I will take a look at deploying the page via a github action. That would allows us to control more of the deployment, and we could maybe use something like `nbconvert` to convert the `.ipynb` files directly to html automatically before deployment. That would avoid having to keep both files up to date. 

The action could also refresh the binder instance on push (if binder does not do that automatically).

I see a cosmetic disadvantage though since jupyter notebook files do look different from our regular markdown files. So we would have an aesthetic inconsistency there.

While I do that, our documentation will be on branch `gh-pages-backup`; so you will have to render it locally to look at it.

**Comment by rheitjoh** [comment]
Okay, from looking at other repositories that use binder it seems like the way it works is that you include a link that will then spin up a binder instance. So the github action does not help with this. I will probably stick with the regular GitHub Pages Jekyll integration for now.

**Comment by rheitjoh** [comment]
Okay I added binder links to the 5-minute tutorial and pairing tutorial pages plus a Dockerfile that enables using the IJava Kernel to run the notebooks with Java support. Of course, the libraries are currently not resolvable.

@JanBobolz Could you maybe upload the picture you use in the pairing tutorial?

**Comment by JanBobolz** [comment]
> @JanBobolz Could you maybe upload the picture you use in the pairing tutorial?

It's included in the ipynb file here: https://github.com/upbcuk/upbcuk.github.io/blob/gh-pages/getting-started/pairing-tutorial.ipynb - you can convert it to an external file if needed :)

**Comment by rheitjoh** [comment]
I think these issues have been addressed for a while now (markdown files render properly and we link to a binder instance).
