### ISSUE TITLE
Explain setting of gradle parameter

### ISSUE THREAD

**Issue by JanBobolz** [cryptimeleon/cryptimeleon.github.io#27]
Please add an example how to set "useCurrentBranch" in settings.gradle to the [Composite build](https://cryptimeleon.org/contributors/composite-builds.html) page. 

Questions:
- in which project do I set this parameter? If my project "`includeBuild`-depends" on math and craco, can I turn it off in my project or do I need to modify `craco`'s settings.gradle?
- what's the right syntax to "set" it? Add a concrete code example.

As it stands, it was easier for me to comment out the line that throws an exception rather than read into gradle syntax for setting properties (naive attempts failed). The documentation should be more helpful here.

**Comment by JanBobolz** [comment]
Ah. https://github.com/cryptimeleon/craco/blob/develop/GRADLE_BUILD.md interestingly explains it.

**Comment by rheitjoh** [comment]
We could also make `useCurrentBranch` the default. I always have it on, personally.

**Comment by JanBobolz** [comment]
hmm, I like the current default. It sometimes gets in the way, but I think it's probably the "safe" option to throw errors if you're on a weird branch.
