### ISSUE TITLE
Improve representation page

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/cryptimeleon.github.io#7]
It seems like the representation page in the docs could use some improvements.

What I think could be improved:
- Improve explanation of motivation for using representations
- Make the tutorial a bit less terse, i.e. more verbose and indepth explanations
- Explain serialization and deserialization separately
- Explain how to create a custom representation restorer
- Explain how to manually create a representation instead of using `ReprUtil` since a few classes still use that

**Comment by JanBobolz** [comment]
I like the idea of showing how to do serialization by hand and _then_ introducing the annotation framework. I think this probably makes things easier to understand overall because there's less magic involved overall.

Your other points sound great, too!

**Comment by rheitjoh** [comment]
Whether to introduce `ReprUtil` and then the manual approach or the other way around is an interesting question.
While writing the tutorials for both I have noticed that the `ReprUtil` approach is actually quite complicated compared to just doing it manually, especially if you also consider the advanced syntax supported for the restorer argument. 

The notion of "take a ObjectRepresentation and then put your fields into it" does seem simpler. And the `ReprUtil` approach does not really save that much space in the example I have chosen. One difficulty I see with the manual approach is that, for example for the `ZpElement` representation rdeserialization, you need to either be aware of the `getElement` method in `Zp`, or know how to use `recreateFromRepresentation`. This might present some problems for the user.

I am writing both in a way that is self-contained and does not rely on the user having read the tutorial for the other approach. Then we can still make changes if we want too.

I am also planning on adding a section on representation restorers. Currently the `ReprUtil` tutorial explains some parts of the `RepresentationRestorer` interface, but I think it would be better to have a separate section. This way the tutorials can be a bit shorter, and the representation restorer section can offer a better explanation anyways. This could also cover the issue I raised above on the issues with the manual approach tutorial, i.e. having to potentially explain `recreateFromRepresentation`.

I would also like to add a section on the `Converter` classes. After all, serialization is not useful without that.

**Comment by JanBobolz** [comment]
Just to be clear: I don't think anyone should ever manually call `recreateFromRepresentation`.
